### ISSUE TITLE
Build error with install.sh Apple. 

### ISSUE THREAD

**Issue by 7etsuo** [mkt3/dotfiles#11]
Getting the following error on my Apple m1 13.4.1 (22F82)

`curl -sL https://raw.githubusercontent.com/mkt3/dotfiles/main/install.sh | sh -s gui dev`

```
[100%] Linking C shared module pam_reattach.so
ld: warning: directory not found for option '-L/opt/homebrew/opt/libgccjit/lib/gcc/11'
[100%] Built target pam_reattach
Install the project...
-- Install configuration: "Release"
CMake Error at cmake_install.cmake:41 (file):
  file cannot create directory: /usr/local/lib.  Maybe need administrative
  privileges.


make: *** [install] Error 1
```
By the way I love your dot files, I'm currently using your setup on Archlinux. Thought i'd give it a go on my mac as well.

**Comment by 7etsuo** [comment]
one work around would be to run the following command
`curl -sL https://raw.githubusercontent.com/mkt3/dotfiles/main/install.sh | sudo sh -s gui dev`

 However this will then attempt to run brew install as root after which is disabled. Possibly splitting the setup into stages would be a good solution here ?

**Comment by mkt3** [comment]
@snowcra5h 
Thank you for raising the issue. 
I didn't notice the problem because my local macOS runs on x86_64. 

It seems there's an issue with permission errors when installing pam-reattach. I've fixed this in the latest main branch. 

If you'd like, please give it a try.
