### ISSUE TITLE
Brew install issues. MacOS

### ISSUE THREAD

**Issue by 7etsuo** [mkt3/dotfiles#12]
The following need to be fixed. 

```
Installing koekeishiya/formulae/yabai
Warning: 'koekeishiya/formulae/yabai' formula is unreadable: No available formula with the name "koekeishiya/formulae/yabai".
Please tap it and then try again: brew tap koekeishiya/formulae
```

```
Installing koekeishiya/formulae/skhd
Warning: 'koekeishiya/formulae/skhd' formula is unreadable: No available formula with the name "koekeishiya/formulae/skhd".
```

Changing these to `homebrew-formulae/yabai` and `homebrew-formulae/skhd` should do it. I will test this, and put in a pull request. 

There are also user related issues.
from the following lines in the brew install file
```
mas "Kindle", id: 405399194
mas "Slack", id: 803453959
mas "The Unarchiver", id: 425424353
mas "Enpass", id: 732710998
mas "Sequel Ace", id: 1518036000
mas "GoodNotes", id: 1444383602
mas "Dictonaries", id: 1380563956
mas "MeetingBar", id: 1532419400
mas "WireGuard", id: 1451685025
mas "Bitwarden", id: 1352778147
```

The error message is as follows:
```
This redownload is not available for this Apple ID either because it was bought by a different user or the item was refunded or cancelled.
```

The error message suggests that the app we are trying to install with `mas` wasn't originally purchased with the Apple ID the user is currently logged into. I'm not sure what a solution for this would be as i'm not familiar with mas. 

```
Error: No downloads began
No downloads
Installing Kindle has failed!
Installing Slack
Error: No downloads began
No downloads
Installing Slack has failed!
Installing The Unarchiver
Installing Enpass
Error: No downloads began
No downloads
Installing Enpass has failed!
Installing Sequel Ace
Error: No downloads began
No downloads
Installing Sequel Ace has failed!
Installing GoodNotes
Error: No downloads began
No downloads
Installing GoodNotes has failed!
Installing Dictonaries
Error: No downloads began
No downloads
Installing Dictonaries has failed!
Installing MeetingBar
Error: No downloads began
No downloads
Installing MeetingBar has failed!
Installing WireGuard
Installing Bitwarden
Error: No downloads began
No downloads
Installing Bitwarden has failed!
Homebrew Bundle failed! 8 Brewfile dependencies failed to install.
```

**Comment by snowcra5h** [comment]
Edit, as it says in the readme.md you have to be logged into the App Store. My mistake (and i'd imagine other people may fall into this trap as well) was assuming being logged in on the guy was enough but you actually have to sign in. This still doesn't correct the first issue though with `yabai` and `skhd`

**Comment by mkt3** [comment]
@snowcra5h 
Thank you for your issue. As you pointed out two problems, I will write them separately.

The warnings for yabai and skhd are only displayed upon the first installation. They will not appear from the second installation onward, so there is no problem there.

Also, on the yabai and skhd GitHub pages, the following commands are recommended:
`brew install koekeishiya/formulae/yabai` and `brew install koekeishiya/formulae/skhd`.

You can find more information on these pages:
https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
https://github.com/koekeishiya/skhd

**Comment by mkt3** [comment]
Regarding mas, have you already `signed into the App Store manually`? If the issue persists even after doing so, you may need to install the relevant software manually from the App Store once.

These software I have listed to install via mas are the ones I need.
 If any of them are unnecessary for you, please feel free to remove the corresponding line from `files/homebrew/Brewfile`.
 
 Thanks.

**Comment by 7etsuo** [comment]
> Regarding mas, have you already `signed into the App Store manually`? If the issue persists even after doing so, you may need to install the relevant software manually from the App Store once.
> 
> These software I have listed to install via mas are the ones I need. If any of them are unnecessary for you, please feel free to remove the corresponding line from `files/homebrew/Brewfile`.
> 
> Thanks.

I installed the relevant software manually with was a good work around.
