### ISSUE TITLE
Errors can't find terminal definition for tmux-256color

### ISSUE THREAD

**Issue by 7etsuo** [mkt3/dotfiles#14]
I was getting the error mentioned in the header I was able to correct this by making a script named `tux-256color.termino` and then adding the new terminal definition to my system's `terminfo` database.

The contents of the file will depend on what terminal features you want to support. For `tmux-256color`, you can start with the `xterm-256color` definition and add the` tmux-specific` capabilities. This is what worked for me. 

```
# Save this in a file called tmux-256color.terminfo
tmux|tmux terminal multiplexer,
  ritm=\E[23m, rmso=\E[27m, sitm=\E[3m, smso=\E[7m,
  use=xterm-256color, use=screen,
tmux-256color|tmux with 256 colors,
  use=xterm-256color, use=tmux,
```

Next, compile this file with the tic command. This will add the terminal definition to your user's terminfo database: `tic -x tmux-256color.terminfo` 

You should now be able to use `tmux-256color` as a value for the `TERM` environment variable. Please let me know if there is a better way to do this.

**Comment by mkt3** [comment]
@snowcra5h 
Thank you for bringing up the issue. 

I had been manually adding it just for the initial run, so this is a good opportunity to integrate it into the script as you suggested. 

I don't currently have an M1 mac, so I haven't been able to test it, but I believe it should work.
 If you're okay with it, please give it a try.
https://github.com/mkt3/dotfiles/commit/8e444df1318a5d16d2d0b487f7ea69ac594f0b66
